### ISSUE TITLE
Where the fuck are those contexts

### ISSUE THREAD

**Issue by LeChatErrant** [antoinefamibelle/FreelanceKillerBack#8]
Hi ! It's me again 😇

It's been two hours and I still can't find those god damn contexts your are talking about in your codebase

Just to be clear, in [user.helper.ts](https://github.com/antoinefamibelle/FreelanceKillerBack/blob/main/src/app/user/user.helper.ts), you're aware that CTX stands for CONTEXT right ??

Have a nice day, I hate you

**Comment by antoinefamibelle** [comment]
Hi again ! 

Yeah I know that but I'm coding the same way that you were looking for a job in a ✨crappy way✨

Hate you too little cat
