### ISSUE TITLE
Weird comments convention

### ISSUE THREAD

**Issue by LeChatErrant** [antoinefamibelle/FreelanceKillerBack#9]
I noticed you're using JSDoc comments ;)
When I look at the JSDoc documentation, I observe that those comments are expressed using 
```
/**
 * 
 */
```

But instead, you're using a weird convention : 
```
/**
 * 
 **/
```

It's funny how it reminds me of an other developer I used to work with 🤔
I wonder if you may happen to know him

Anyway, have a nice day !

**Comment by antoinefamibelle** [comment]
Oh yeah this is for one time a pretty usefull issue ! 

Thank you (You are the reason why I hate cat just to let you know)
